encoding: utf-8
timezone: Europe/Berlin

baseurl: http://markdown-syntax.de

gems:
  - jekyll-sitemap
  - jekyll-redirect-from

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      author: Dirk Einecke

navigation:
  - text: Was ist Markdown?
    path: /Was-ist-Markdown/
  - text: Wozu Markdown verwenden?
    path: /Wozu-Markdown-verwenden/
  - text: Markdown-Implementierungen
    path: /Markdown-Implementierungen/
  - text: Syntax
    path: /Syntax/
    items:
      - text: Überschriften
        path: /Syntax/Ueberschriften/
      - text: Zitate
        path: /Syntax/Zitate/
      - text: Horizontale Linien
        path: /Syntax/Horizontale-Linien/
      - text: Absätze
        path: /Syntax/Absaetze/
      - text: Zeilenumbrüche
        path: /Syntax/Zeilenumbrueche/
      - text: Automatische Verlinkungen
        path: /Syntax/Automatische-Verlinkungen/
